server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: facture-service
          uri: lb://FACTURE-SERVICE
          predicates:
            - Path=/api/factures/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/clients/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: produit-service
          uri: lb://PRODUIT-SERVICE
          predicates:
            - Path=/api/produits/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
